# Server
quarkus.http.port=8080
quarkus.application.name=sentinel-api-gateway
quarkus.application.version=1.0.0

# Connector global config (clave)
mp.messaging.connector.smallrye-rabbitmq.host=rabbitmq
mp.messaging.connector.smallrye-rabbitmq.port=5672
mp.messaging.connector.smallrye-rabbitmq.username=sentinel
mp.messaging.connector.smallrye-rabbitmq.password=sentinel

# Channel config
mp.messaging.outgoing.pending-checks.connector=smallrye-rabbitmq
mp.messaging.outgoing.pending-checks.exchange.name=pending_checks
mp.messaging.outgoing.pending-checks.exchange.type=direct
mp.messaging.outgoing.pending-checks.routing-key=pending_checks
mp.messaging.outgoing.pending-checks.exchange.declare=true

# Logging / OpenAPI / Health
quarkus.log.level=INFO
quarkus.log.category."com.sentinel".level=DEBUG
quarkus.log.console.enable=true
quarkus.smallrye-openapi.info-title=Sentinel-Mesh API Gateway
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.always-include=true
quarkus.smallrye-health.root-path=/health